# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: omgtex 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "omgtex"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Lucas Jen\u{df}"]
  s.cert_chain = ["certs/fresskoma.pem"]
  s.date = "2016-09-06"
  s.description = "Builds your *TeX files by running *tex an appropriate amount of times"
  s.email = "public@x3ro.de"
  s.executables = ["omgtex"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/omgtex",
    "lib/omgtex.rb",
    "lib/omgtex/options.rb",
    "lib/omgtex/runner.rb",
    "omgtex.gemspec",
    "test/helper.rb",
    "test/test_omgtex.rb"
  ]
  s.homepage = "http://github.com/x3ro/omgtex"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.signing_key = "/Users/lucas/.ssh/keys/rubygems/gem-private_key.pem"
  s.summary = "Essentially runs *TeX the appropriate number of times"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.1"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.1"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.1"])
  end
end

