# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: omgtex 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "omgtex".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Lucas Jen\u00DF".freeze]
  s.cert_chain = ["certs/fresskoma.pem".freeze]
  s.date = "2020-07-09"
  s.description = "Builds your *TeX files by running *tex an appropriate amount of times".freeze
  s.email = "public@x3ro.de".freeze
  s.executables = ["omgtex".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/omgtex",
    "certs/fresskoma.pem",
    "lib/omgtex.rb",
    "lib/omgtex/options.rb",
    "lib/omgtex/runner.rb",
    "omgtex.gemspec",
    "test/helper.rb",
    "test/test_omgtex.rb"
  ]
  s.homepage = "http://github.com/x3ro/omgtex".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.6".freeze
  s.signing_key = "/Users/lucas.jenss/.ssh/keys/rubygems/gem-private_key.pem".freeze
  s.summary = "Essentially runs *TeX the appropriate number of times".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>.freeze, ["~> 2.1.4"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    else
      s.add_dependency(%q<bundler>.freeze, ["~> 2.1.4"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    end
  else
    s.add_dependency(%q<bundler>.freeze, ["~> 2.1.4"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
  end
end

